baseURL: "/"
title: "Ismail Saifudin | Security Resume"
languageCode: en-us
disableKinds: [taxonomy, term, page, section, RSS, sitemap, robotsTXT, "404"]
theme: resume-a4

params:
  useFontAwesome: true
  externalLinkIcon: true
  favicon: true

  header:
    useFontAwesome: true
    contactOnSide: false
    avatar: avatar.jpg
    contact: true
    tagline: true
    links: true

  pages:
    - header: true
      side:
        - feature: skills
          title: Security Capabilities
          widget: word-list
          style: compact
        - feature: certificates
          title: Certifications & Training
      features:
        - feature: about
          title: About Me
        - feature: experience

    - header: true
      side:
        - feature: education
      features:
        - feature: experience
          title: Experience (Continued)

  experience:
    grouped: false
    tools:
      show: false
      title: Technologies

  education:
    useFontAwesome: true
    externalLinkIcon: false
    location:
      show: false
    details:
      show: false
    namePrimary: false

  itemTitle:
    useFontAwesome: false
    externalLinkIcon: false

  footer:
    show: false
    credits: false
